#encoding:utf-8
from selenium import webdriver
from time import sleep
import win32api, win32pdhutil, win32con
import win32com.client
from win32com.client import Dispatch
profile=webdriver.FirefoxProfile(r"C:\Users\Administrator\AppData\Roaming\Mozilla\Firefox\Profiles\24iktfsp.test")
br=webdriver.Firefox(firefox_profile=profile)
br.get("http://sso.xnwmall.com/mall/login.shtml")
br.maximize_window()
sleep(5)
br.find_element_by_css_selector("input.text_input.text_input_h.input_xlarge").send_keys('15077777777')

br.find_element_by_id("password").send_keys("wwg111")
br.find_element_by_id("subLoginBtn").click()
sleep(5)
br.find_element_by_link_text(u"商家入口").click()
sleep(3)
br.switch_to_window(br.window_handles[-1])
br.find_element_by_link_text(u"发布商品").click()
sleep(2)
br.find_element_by_xpath("//*[@data-id='71e7fdb9714c4c30a320dedfc3b77a12']").click()
sleep(2)
br.find_element_by_xpath("//*[@data-id='bd74e1312c2a4b79b2fdcab28068d9ec']").click()
sleep(2)
br.find_element_by_xpath("//*[@data-id='6daa92f9e9644d04a8841c7ed89981a4']").click()
br.find_element_by_xpath("//*[@id='next']/strong").click()
sleep(2)
br.find_element_by_id("proName").send_keys("wwg1")
br.find_element_by_css_selector("input.text_input.input_small.fl.keyword").send_keys("wwg2")
br.find_element_by_id("proDesc").send_keys("wwg3")
autoit = Dispatch("AutoItX3.Control")
str_filepath ="G:\\animal_white_baby_dogs_2_1920x1200_5693_2.jpg"
br.find_element_by_id("uploadimgList1SRC").click()
br.find_element_by_css_selector("input[type='file']").click()
autoit.WinWait(u"文件上传", "", 5)
autoit.WinActivate(u"文件上传")
autoit.ControlSetText(u"文件上传","","[CLASS:Edit; INSTANCE:1]",str_filepath)
autoit.ControlClick(u"文件上传","",1) #附件上传动作
sleep(2)
br.find_element_by_css_selector("a.mot_btn_box._mask_upload").click()
sleep(2)
br.find_element_by_id("proNum").send_keys("wwg4")
br.find_element_by_css_selector("option[value='3575b87aadee4cfab86c003669479b00'").click()
br.find_element_by_id("proBeginWeight").send_keys("22")
br.find_element_by_css_selector("input.text_input.mulSize_key").send_keys(u"包装")
br.find_element_by_css_selector("input.text_input.mulSize_val").send_keys(u"精装 散装")
br.find_element_by_xpath("//*[@class='btn w_94 nextStep']/strong").click()
br.find_element_by_xpath("//*[@class='checkoutCon multiSize_TAB']/dd[1]/div[2]/input").send_keys('1')
br.find_element_by_xpath("//*[@class='checkoutCon multiSize_TAB']/dd[1]/div[3]/input").send_keys('2')
br.find_element_by_xpath("//*[@class='checkoutCon multiSize_TAB']/dd[1]/div[4]/input").send_keys('3')
br.find_element_by_xpath("//*[@class='checkoutCon multiSize_TAB']/dd[2]/div[2]/input").send_keys('4')
br.find_element_by_xpath("//*[@class='checkoutCon multiSize_TAB']/dd[2]/div[3]/input").send_keys('5')
br.find_element_by_xpath("//*[@class='checkoutCon multiSize_TAB']/dd[2]/div[4]/input").send_keys('6')
js="document.getElementsByClassName(\"ke-edit-iframe\")[0].contentWindow.document.body.innerHTML=\"%s\"" %("王伟高测试")
br.execute_script(js)
br.find_element_by_css_selector("span.ke-toolbar-icon.ke-toolbar-icon-url.ke-icon-justifyleft").click()
br.find_element_by_id("saveProBtn2").click()
# br.find_element_by_xpath("//*[@id='saveProBtn']/strong").click()
sleep(5)
br.switch_to_alert().accept()
